### PR TITLE
Add configurability for precompiled deps usage

### PR DESCRIPTION
**Pull request by anzaika**
Hi!

I figured sometimes you just want to use the binaries already present on your system. So this configurability should be worth it. Please let me know what you think.

As always many thanks for all the insanely work you are doing.

### CODE REVIEW

**Comment by mat-hek** [comment]
Hi, good idea ;) I thought about doing it in Bundlex, so you could do something like

```elixir
config :bundlex, :use_local_natives, "opus"
```

That way it would work everywhere out of the box. What do you think?

**Comment by anzaika** [comment]
Hi @mat-hek!

Thanks a lot for your comment.

I think in the real world people either install all the necessary packages themselves or expect "batteries to be included". Hence the solution you propose would be very efficient.

The only thing I'm worried about is that it leaves no "escape hatch" for the minority of users who might want to use that specific version of the OPUS library they have modified and built themselves. Do you think this might be the case?

**Comment by mat-hek** [comment]
Hmm, not sure if I follow. I wanted to say that if we implement this in Bundlex, you can do 

```elixir
config :bundlex, :use_local_natives, "opus"
```

and have the dependency loaded from the OS - that would be the escape hatch. It would work for other libs as well, like

```elixir
config :bundlex, :use_local_natives, "swresample"
```

;)

**Comment by anzaika** [comment]
Oh now I get it, that sounds like a perfect solution. I would be happy to contribute that to Bundlex as well if no-one is currently working on it.

**Comment by mat-hek** [comment]
@anzaika great, go for it! I'm still unsure about the config key though. Maybe `enforce_pkg_config` would be better than `use_local_natives`?

**Comment by mat-hek** [comment]
Done in https://github.com/membraneframework/bundlex/pull/113

**Pull request closed without merging**
